### ISSUE TITLE
Breaks on Python 3.2

### ISSUE THREAD

**Issue by Fantomas42** [textile/python-textile#11]
Hello,

I suppose that is not big priority to support Python 3.2, but since this commit on this line: https://github.com/textile/python-textile/commit/1e5d98e5bedbc09939e0a506e6a4367fe56309e0#diff-bcabf8c90bd02845f81578f71c50c091R63 I could not install the library.

So I'm stuck with the version 2.1.5 of the library.

This issue only happen on Python 3.2, the version 3.1, 3.3, 3.4 are not affected.

Traceback on a Travis build: 
https://travis-ci.org/Fantomas42/django-blog-zinnia/jobs/33796226#L249

Regards

**Comment by ikirudennis** [comment]
Hey, @Fantomas42 and anyone else who might be py32:  Do you still need support for that version?  There are other projects that are dropping support for it, and I think some new code doesn't work, and it's becoming more difficult to test against it.  I've taken it out of travis while I've been doing some updates, since it was only returning errors.  I'll add it back and see how it goes, but the next version may not support py32.

**Comment by ikirudennis** [comment]
Scratch that, I've got it all working again for py32.
