### ISSUE TITLE
Missing test files on pypi

### ISSUE THREAD

**Issue by sebix** [textile/python-textile#59]
The file on pypi/pythonhosted does not include the tests, just the tests/fixtures/README.txt file. However when I locally execute `python setup.py sdist` all the tests are included, so the MANIFEST.in file should be correct. Do you know what's wrong here?

**Comment by ikirudennis** [comment]
I have no idea. The only difference is that I built yesterday's upload from a different cloned directory than what I usually use. I git pulled into my usual directory, and ran the same `python setup.py sdist` and everything worked fine just now. Since there's no change to the code, I'm just going to upload that sdist now. That shouldn't cause any problems, right?

**Comment by ikirudennis** [comment]
I uploaded it as textile-3.0.0-withtests.tar.gz

**Comment by thmo** [comment]
There are more files missing, see #60.
